name: GuardDogs
version: 0.8.0-SNAPSHOT
main: me.ardimaster.guarddogs.GuardDogs
author: ArdiMaster

commands:
  guarddogs:
    description: Administrative stuff for GuardDogs.
    usage: /guarddogs help
    permission: guarddogs.admin

permissions:
  guarddogs.admin:
    description: Allows you to modify the items required for guard dogs.
    default: op