name: GuardDogs
version: 0.7
main: org.bitbucket.ardimaster.guarddogs.GuardDogs
author: ArdiMaster

commands:
  guarddogs:
    usage: /guarddogs help

permissions:
  guarddogs.admin:
    description: Allows you to modify the items required for guard dogs.
    default: op