name: GuardDogs
version: 0.6.5
main: org.bitbucket.ardimaster.guarddogs.GuardDogs
author: ArdiMaster

commands:
  guarddogs:
    usage: /guarddogs [create|disable|ignore] [Material]

permissions:
  guarddogs.admin:
    description: Allows you to modify the items required for guard dogs.
    default: op